In [1]:
import sympy as sym
import numpy as np
from IPython.display import display,Math

In [9]:
A = np.array([ [1,2],[3,4] ])

print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [16]:
mat = np.zeros([4,6])

mat[0,1] = 2
mat[2,4] = 7

mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [41]:
import sympy as sym
import numpy as np
from IPython.display import display,Math
from sympy.abc import x,y

size = list(range(3))
matrix = np.zeros([len(size),len(size)])

expr = (4+x)*(2-y)
display(Math('f(x,y)=(4+x)(2-y)'))
display(Math('x,y\\in\{%s\}' %','.join([str(number) for number in size])))

def f(x_arg,y_arg):
    matrix[x_arg,y_arg] = expr.subs({x:x_arg, y:y_arg})

for x_val in size:
    for y_val in size:
        f(x_val,y_val)

display(Math(sym.latex(sym.simplify(matrix))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>